# SPDX-License-Identifier: MIT
# Copyright (c) 2012-2026 Thiago de Freitas (https://github.com/thiagodefreitas)
"""Cross-validation against the published test suites of NIST SP 1065.

W. J. Riley, *Handbook of Frequency Stability Analysis*, NIST Special
Publication 1065 (2008), section 12:

* Table 30: the nine-point frequency data of NBS Monograph 140, Annex 8.E,
  at averaging factors 1 and 2;
* Table 31: the 1000-point frequency test suite generated by
  ``n[i+1] = 16807 * n[i] mod 2147483647`` from ``n[0] = 1234567890``
  (divided by 2147483647), at averaging factors 1, 10 and 100.

Frequency data are converted to phase with tau0 = 1 (mean removed, which
none of these statistics depend on). The tables print 7 significant digits.
"""

import numpy as np
import pytest

from ntpstats import stability as st

REL = 5e-7  # tables print 7 significant digits

NBS9 = [892, 809, 823, 798, 671, 644, 883, 903, 677]
TABLE30 = {  # averaging factors 1, 2
    "adev": [91.22945, 115.8082],
    "oadev": [91.22945, 85.95287],
    "mdev": [91.22945, 74.78849],
    "tdev": [52.67135, 86.35831],
    "hdev": [70.80607, 85.61487],  # overlapping Hadamard
    "totdev": [91.22945, 93.90379],
    "mtot": [75.50203, 75.83606],
    "ttot": [43.59112, 87.56794],
}
TABLE31 = {  # averaging factors 1, 10, 100
    "adev": [2.922319e-01, 9.965736e-02, 3.897804e-02],
    "oadev": [2.922319e-01, 9.159953e-02, 3.241343e-02],
    "mdev": [2.922319e-01, 6.172376e-02, 2.170921e-02],
    "tdev": [1.687202e-01, 3.563623e-01, 1.253382e00],
    "hdev": [2.943883e-01, 9.581083e-02, 3.237638e-02],
    "totdev": [2.922319e-01, 9.134743e-02, 3.406530e-02],
    "mtot": [2.418528e-01, 6.499161e-02, 2.287774e-02],
    "ttot": [1.396338e-01, 3.752293e-01, 1.320847e00],
}


def nist1000():
    n, out = 1234567890, []
    for _ in range(1000):
        out.append(n / 2147483647)
        n = (16807 * n) % 2147483647
    return np.array(out)


def to_phase(y):
    y = np.asarray(y, dtype=float)
    return np.concatenate(([0.0], np.cumsum(y - y.mean())))


def test_nist1000_generator_matches_table31_summary():
    y = nist1000()
    assert y[0] == pytest.approx(0.5748904732, rel=1e-9)
    assert y.max() == pytest.approx(9.957453e-01, rel=REL)
    assert y.min() == pytest.approx(1.371760e-03, rel=REL)
    assert y.mean() == pytest.approx(4.897745e-01, rel=REL)
    assert y.std(ddof=1) == pytest.approx(2.884664e-01, rel=REL)


@pytest.mark.parametrize("kind", sorted(TABLE30))
def test_nbs_monograph_140(kind):
    r = st.compute(to_phase(NBS9), 1.0, kind, [1, 2], ci=None, min_terms=1)
    np.testing.assert_allclose(r.dev, TABLE30[kind], rtol=REL)


@pytest.mark.parametrize("kind", sorted(TABLE31))
def test_nist_1000_point_suite(kind):
    r = st.compute(to_phase(nist1000()), 1.0, kind, [1, 10, 100], ci=None, min_terms=1)
    np.testing.assert_allclose(r.dev, TABLE31[kind], rtol=REL)


def test_mtot_published_values_are_bias_corrected():
    # The tables list MTOT divided by the white-FM bias factor 0.73; the raw
    # SP 1065 eq. (27) value is available with bias_correction=False.
    x = to_phase(nist1000())
    raw = st.compute(x, 1.0, "mtot", [1, 10, 100], ci=None, min_terms=1, bias_correction=False)
    np.testing.assert_allclose(raw.dev / np.sqrt(st.MTOT_BIAS[0]), TABLE31["mtot"], rtol=REL)
    cooked = st.compute(x, 1.0, "mtot", [1, 10, 100], ci=None, min_terms=1)
    assert cooked.meta["bias_factor"] == [0.73, 0.73, 0.73]
