#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2012-2026 Thiago de Freitas (https://github.com/thiagodefreitas)
"""Render the repository documentation as GitHub wiki pages.

    python docs/sync_wiki.py OUTPUT_DIR

The wiki is generated, not edited: ``docs/*.md``, ``CHANGELOG.md`` and
``ROADMAP.md`` are the source of truth. Links between pages become wiki links,
images and repository paths become absolute GitHub URLs, MkDocs admonitions
become block quotes, and the API pages (rendered from docstrings by
mkdocstrings) point to the documentation site. ``_Sidebar.md`` and
``_Footer.md`` are generated too. Pages that are no longer generated are
removed from OUTPUT_DIR; other files there are left alone.
"""

from __future__ import annotations

import os
import re
import sys

REPO = "thiagodefreitas/NetworkTime"
BRANCH = "master"
SITE = "https://thiagodefreitas.github.io/NetworkTime/"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#: source (relative to the repository root) -> wiki page name
PAGES = {
    "docs/index.md": "Home",
    "docs/getting-started.md": "Getting-Started",
    "docs/cli.md": "CLI-Reference",
    "docs/formats.md": "Input-Formats",
    "docs/statistics.md": "Statistics",
    "docs/network.md": "Network-and-Estimators",
    "docs/ptp.md": "PTP-and-Time-Error",
    "docs/sources.md": "Sources-Instruments-Bounds",
    "docs/assurance.md": "Audit-Events-CI",
    "docs/monitoring.md": "Monitoring",
    "docs/protocols.md": "Protocols",
    "docs/validation.md": "Validation",
    "docs/migrating.md": "Stable32-TimeLab-allantools",
    "docs/api/index.md": "API-Reference",
    "docs/INTEROP.md": "Live-Interop",
    "docs/STATE_OF_THE_ART.md": "State-of-the-Art",
    "docs/LANDSCAPE.md": "Tools-Landscape",
    "CHANGELOG.md": "Changelog",
    "ROADMAP.md": "Roadmap",
}
SIDEBAR = [
    ("Home", "Home"), ("Getting started", "Getting-Started"), ("CLI reference", "CLI-Reference"),
    ("Input formats", "Input-Formats"), ("Statistics", "Statistics"),
    ("Network & estimators", "Network-and-Estimators"), ("PTP & time error", "PTP-and-Time-Error"), ("Sources & bounds", "Sources-Instruments-Bounds"), ("Audit, events & CI", "Audit-Events-CI"), ("Monitoring", "Monitoring"), ("Protocols", "Protocols"), ("Validation", "Validation"),
    ("API reference", "API-Reference"), ("Live interop", "Live-Interop"),
    ("State of the art", "State-of-the-Art"), ("Tools landscape", "Tools-Landscape"), ("Changelog", "Changelog"), ("Roadmap", "Roadmap"),
]
GENERATED_MARK = "<!-- generated by docs/sync_wiki.py -->"
_LINK = re.compile(r"(!?)\[([^\]]*)\]\(([^)\s]+)\)")


def _resolve(src: str, target: str) -> str:
    """Rewrite one link target found in ``src`` (a repository-relative path)."""
    if re.match(r"^[a-z]+:|^#|^mailto:", target):
        return target
    path, _, anchor = target.partition("#")
    anchor = f"#{anchor}" if anchor else ""
    full = os.path.normpath(os.path.join(os.path.dirname(src), path)).replace(os.sep, "/")
    if full in PAGES:
        return PAGES[full] + anchor
    if full.startswith("docs/api/") and full.endswith(".md"):  # mkdocstrings pages live on the site
        return f"{SITE}api/{os.path.basename(full)[:-3]}/{anchor}"
    if full.startswith("docs/") and full.endswith(".md"):
        return f"{SITE}{full[5:-3]}/{anchor}"
    return f"https://github.com/{REPO}/blob/{BRANCH}/{full}{anchor}"


def _image(src: str, target: str) -> str:
    if re.match(r"^[a-z]+:", target):
        return target
    full = os.path.normpath(os.path.join(os.path.dirname(src), target)).replace(os.sep, "/")
    return f"https://raw.githubusercontent.com/{REPO}/{BRANCH}/{full}"


def _admonitions(text: str) -> str:
    """``!!! warning`` + indented body -> ``> **Warning:** body``."""
    out, lines, i = [], text.split("\n"), 0
    while i < len(lines):
        m = re.match(r"^!!! (\w+)(?: \"([^\"]*)\")?\s*$", lines[i])
        if not m:
            out.append(lines[i])
            i += 1
            continue
        title = m.group(2) or m.group(1).capitalize()
        body = []
        i += 1
        while i < len(lines) and (lines[i].startswith("    ") or not lines[i].strip()):
            if not lines[i].strip() and (i + 1 >= len(lines) or not lines[i + 1].startswith("    ")):
                break
            body.append(lines[i][4:])
            i += 1
        out.append(f"> **{title}:** " + " ".join(b.strip() for b in body if b.strip()))
    return "\n".join(out)


def convert(src: str, text: str) -> str:
    def repl(m):
        bang, label, target = m.groups()
        new = _image(src, target) if bang else _resolve(src, target)
        return f"{bang}[{label}]({new})"

    text = _LINK.sub(repl, text)
    text = re.sub(r"^::: .*$", "", text, flags=re.M)  # mkdocstrings directives
    text = _admonitions(text)
    return f"{GENERATED_MARK}\n{text.rstrip()}\n"


def sidebar() -> str:
    items = "\n".join(f"- [{label}]({page})" for label, page in SIDEBAR)
    return (f"{GENERATED_MARK}\n**ntpstats**\n\n{items}\n\n"
            f"[Documentation site]({SITE}) · [Repository](https://github.com/{REPO})\n")


def footer() -> str:
    return (f"{GENERATED_MARK}\nGenerated from the repository's `docs/`, `CHANGELOG.md` and `ROADMAP.md`. "
            f"Edit those files (pull requests welcome), not the wiki. "
            f"ntpstats · MIT © 2012–2026 Thiago de Freitas\n")


def build(out_dir: str) -> list:
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for src, page in PAGES.items():
        with open(os.path.join(ROOT, src), encoding="utf-8") as fh:
            text = fh.read()
        name = f"{page}.md"
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as fh:
            fh.write(convert(src, text))
        written.append(name)
    for name, content in (("_Sidebar.md", sidebar()), ("_Footer.md", footer())):
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(name)
    # remove pages this script generated earlier but no longer produces
    for name in os.listdir(out_dir):
        path = os.path.join(out_dir, name)
        if name.endswith(".md") and name not in written and os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                if fh.readline().strip() == GENERATED_MARK:
                    os.remove(path)
    return written


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    for n in build(sys.argv[1]):
        print(n)
