# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ntpstats.ui'
#
# Created: Wed Jun  6 18:50:54 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1438, 878)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 1401, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(617, 0))
        self.tab.setObjectName("tab")
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 1371, 541))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setMinimumSize(QtCore.QSize(617, 0))
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotSpace = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.plotSpace.setContentsMargins(0, 0, 0, 0)
        self.plotSpace.setObjectName("plotSpace")
        self.nametoSave = QtGui.QLineEdit(self.tab_2)
        self.nametoSave.setGeometry(QtCore.QRect(640, 50, 271, 27))
        self.nametoSave.setObjectName("nametoSave")
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(650, 30, 241, 17))
        self.label_2.setObjectName("label_2")
        self.sliderOffsets = QtGui.QSlider(self.tab_2)
        self.sliderOffsets.setGeometry(QtCore.QRect(650, 510, 271, 29))
        self.sliderOffsets.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOffsets.setObjectName("sliderOffsets")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 631, 541))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.plotSpace_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.plotSpace_3.setContentsMargins(0, 0, 0, 0)
        self.plotSpace_3.setObjectName("plotSpace_3")
        self.nametoSave_3 = QtGui.QLineEdit(self.tab_3)
        self.nametoSave_3.setGeometry(QtCore.QRect(640, 50, 271, 27))
        self.nametoSave_3.setObjectName("nametoSave_3")
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(650, 30, 241, 17))
        self.label_4.setObjectName("label_4")
        self.sliderOffsets_3 = QtGui.QSlider(self.tab_3)
        self.sliderOffsets_3.setGeometry(QtCore.QRect(650, 510, 271, 29))
        self.sliderOffsets_3.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOffsets_3.setObjectName("sliderOffsets_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 631, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.plotSpace_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.plotSpace_2.setContentsMargins(0, 0, 0, 0)
        self.plotSpace_2.setObjectName("plotSpace_2")
        self.nametoSave_2 = QtGui.QLineEdit(self.tab_4)
        self.nametoSave_2.setGeometry(QtCore.QRect(640, 50, 271, 27))
        self.nametoSave_2.setObjectName("nametoSave_2")
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(650, 30, 231, 17))
        self.label_3.setObjectName("label_3")
        self.sliderHist = QtGui.QSlider(self.tab_4)
        self.sliderHist.setGeometry(QtCore.QRect(650, 510, 271, 29))
        self.sliderHist.setOrientation(QtCore.Qt.Horizontal)
        self.sliderHist.setObjectName("sliderHist")
        self.tabWidget.addTab(self.tab_4, "")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 750, 630, 17))
        self.label.setObjectName("label")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 750, 24, 24))
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setPixmap(QtGui.QPixmap("icons/ntp-client.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1438, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLoad = QtGui.QMenu(self.menuFile)
        self.menuLoad.setObjectName("menuLoad")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.toolBarNTP = QtGui.QToolBar(MainWindow)
        self.toolBarNTP.setEnabled(True)
        self.toolBarNTP.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.toolBarNTP.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBarNTP.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBarNTP.setObjectName("toolBarNTP")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarNTP)
        MainWindow.insertToolBarBreak(self.toolBarNTP)
        self.actionNtpStatus = QtGui.QAction(MainWindow)
        self.actionNtpStatus.setObjectName("actionNtpStatus")
        self.actionLoopstats = QtGui.QAction(MainWindow)
        self.actionLoopstats.setObjectName("actionLoopstats")
        self.actionLog_File = QtGui.QAction(MainWindow)
        self.actionLog_File.setObjectName("actionLog_File")
        self.actionRun_File = QtGui.QAction(MainWindow)
        self.actionRun_File.setObjectName("actionRun_File")
        self.actionPlot = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/plot_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icons/plot_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPlot.setIcon(icon)
        self.actionPlot.setObjectName("actionPlot")
        self.actionLoadLopstats = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/onebit_13.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionLoadLopstats.setIcon(icon1)
        self.actionLoadLopstats.setObjectName("actionLoadLopstats")
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/onebit_11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionLoadLog = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/onebit_14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadLog.setIcon(icon3)
        self.actionLoadLog.setObjectName("actionLoadLog")
        self.actionLoadRun = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/onebit_15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadRun.setIcon(icon4)
        self.actionLoadRun.setObjectName("actionLoadRun")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/onebit_37.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.menuLoad.addAction(self.actionLoopstats)
        self.menuLoad.addAction(self.actionLog_File)
        self.menuLoad.addAction(self.actionRun_File)
        self.menuFile.addAction(self.menuLoad.menuAction())
        self.menuAbout.addAction(self.actionNtpStatus)
        self.menuAbout.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBarNTP.addAction(self.actionLoadLopstats)
        self.toolBarNTP.addAction(self.actionLoadLog)
        self.toolBarNTP.addAction(self.actionLoadRun)
        self.toolBarNTP.addAction(self.actionPlot)
        self.toolBarNTP.addAction(self.actionSave)
        self.toolBarNTP.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NTPStats Analyzer v1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">The contents of the statistics file are going to appear on this space...</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Provide File Name to Save the Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Provide File Name to Save the Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Allan Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Provide File Name to Save the Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Histograms", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Developed by: Thiago de Freitas Oliveira Araujo - Google Summer of Code 2012 - Network Time", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad.setTitle(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarNTP.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBarNTP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNtpStatus.setText(QtGui.QApplication.translate("MainWindow", "NtpStatus", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNtpStatus.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoopstats.setText(QtGui.QApplication.translate("MainWindow", "Loopstats", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoopstats.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog_File.setText(QtGui.QApplication.translate("MainWindow", "Log File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog_File.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_File.setText(QtGui.QApplication.translate("MainWindow", "Run File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_File.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot.setToolTip(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadLopstats.setText(QtGui.QApplication.translate("MainWindow", "loadLoopstats", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadLopstats.setToolTip(QtGui.QApplication.translate("MainWindow", "Load Loopstats File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Save Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadLog.setText(QtGui.QApplication.translate("MainWindow", "loadLog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadLog.setToolTip(QtGui.QApplication.translate("MainWindow", "Load Log File from Estimator Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadRun.setText(QtGui.QApplication.translate("MainWindow", "loadRun", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadRun.setToolTip(QtGui.QApplication.translate("MainWindow", "Load Statistics from Estimator Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))

